version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
    networks:
      - somenet
  mongo:
    container_name: mongo
    image: 'docker.io/bitnami/mongodb:4.2-debian-10'
    ports:
      - "27017:27017"
    networks:
      - somenet
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
      - ./data:/data/db

volumes:
  mongodb_data:
    driver: local

networks:
  somenet:
