version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/app
    ports:
      - "80:3000"
    links:
      - mongo
    networks:
      - somenet
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27007:27017"
    networks:
      - somenet
networks:
  somenet:
